version: '3.9'
services:
  database:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=ayomi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432  
    volumes:
      - db_volume:/var/lib/postgresql

  
volumes:
  db_volume: